src/Entity/Currency.php
<?php

namespace App\Entity;

use App\Repository\CurrencyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=CurrencyRepository::class)
 */
class Currency
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $currency_code;

    /**
     * @ORM\Column(type="decimal", precision=16, scale=8)
     */
    private $exchange_rate;

    public function __construct()
    {
        $this->id = Uuid::v4();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCurrencyCode(): ?string
    {
        return $this->currency_code;
    }

    public function setCurrencyCode(string $currency_code): self
    {
        $this->currency_code = $currency_code;

        return $this;
    }

    public function getExchangeRate(): ?string
    {
        return $this->exchange_rate;
    }

    public function setExchangeRate(string $exchange_rate): self
    {
        $this->exchange_rate = $exchange_rate;

        return $this;
    }
}

src/Controller/NbpController.php
<?php

namespace App\Controller;

use App\Repository\CurrencyRepository;
use App\Service\NbpApiService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NbpController extends AbstractController
{
    /**
     * @Route("/nbp", name="nbp_index")
     */
    public function index(CurrencyRepository $currencyRepo): Response
    {
        return $this->render('nbp/index.html.twig', [
            'items' => $currencyRepo->findAll(),
        ]);
    }

    /**
     * @Route("/nbp/update", name="nbp_update")
     */
    public function update(CurrencyRepository $currencyRepo, NbpApiService $nbp): Response
    {
        return $this->render('nbp/update.html.twig', [
            'result' => $currencyRepo->updateExchangeRates($nbp->getExchangeRates('A')),
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/nbp/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}NbpController{% endblock %}

{% block body %}

<div class="example-wrapper">
  <h1>NbpController ✅ Index</h1>
  <table>
    {% for item in items %}
    <tr>
      <td>{{ item.name }}</td>
      <td>{{ item.currencyCode }}</td>
      <td>{{ item.exchangeRate }}</td>
    </tr>
    {% endfor %}  
  </table>
</div>
{% endblock %}

templates/nbp/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}NbpController{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>NbpController ✅ Update</h1>
    <p>Number of changes: {{ result }}</p>
</div>
{% endblock %}